# Generated by Django 3.1.7 on 2021-04-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('project_id', models.TextField(blank=True, null=True)),
                ('contract_type', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('company_avatar', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('min_qualifications', models.TextField(blank=True, null=True)),
                ('preferred_qualifications', models.TextField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('platform', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('interesting', models.BooleanField(default=False)),
                ('company', models.TextField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
